version: '3.8'

services:
  whisper-api:
    build: .
    container_name: whisper-api
    ports:
      - "9001:9001"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
